<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#torch.Tensor" data-toc-modified-id="torch.Tensor-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>torch.Tensor</a></span><ul class="toc-item"><li><span><a href="#Instentiation-of-Tensor" data-toc-modified-id="Instentiation-of-Tensor-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Instentiation of Tensor</a></span></li><li><span><a href="#Initiation-of-Tensor-using-Factory-Methods" data-toc-modified-id="Initiation-of-Tensor-using-Factory-Methods-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Initiation of Tensor using Factory Methods</a></span></li><li><span><a href="#Random-Initiation-of-Tensor" data-toc-modified-id="Random-Initiation-of-Tensor-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Random Initiation of Tensor</a></span></li><li><span><a href="#Types-and-Attributes" data-toc-modified-id="Types-and-Attributes-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Types and Attributes</a></span></li><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Indexing and Slicing</a></span></li><li><span><a href="#Tensor-Arithmatics" data-toc-modified-id="Tensor-Arithmatics-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Tensor Arithmatics</a></span></li><li><span><a href="#Tensor-Addition" data-toc-modified-id="Tensor-Addition-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Tensor Addition</a></span></li><li><span><a href="#Scalar-Multiplication" data-toc-modified-id="Scalar-Multiplication-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Scalar Multiplication</a></span></li><li><span><a href="#Element-wise-Product/Hadamard-Product" data-toc-modified-id="Element-wise-Product/Hadamard-Product-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Element-wise Product/Hadamard Product</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Usefull-Functions" data-toc-modified-id="Usefull-Functions-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Usefull Functions</a></span><ul class="toc-item"><li><span><a href="#Tensor.data_ptr(...)" data-toc-modified-id="Tensor.data_ptr(...)-1.11.1"><span class="toc-item-num">1.11.1&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/tensors.html" rel="nofollow" target="_blank"><code>Tensor.data_ptr(...)</code></a></a></span></li><li><span><a href="#torch.view(...)" data-toc-modified-id="torch.view(...)-1.11.2"><span class="toc-item-num">1.11.2&nbsp;&nbsp;</span><code>torch.view(...)</code></a></span></li><li><span><a href="#torch.cat(...)" data-toc-modified-id="torch.cat(...)-1.11.3"><span class="toc-item-num">1.11.3&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat" rel="nofollow" target="_blank"><code>torch.cat(...)</code></a></a></span></li><li><span><a href="#-torch.stack(...)" data-toc-modified-id="-torch.stack(...)-1.11.4"><span class="toc-item-num">1.11.4&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.stack.html#torch.stack" rel="nofollow" target="_blank"> <code>torch.stack(...)</code></a></a></span></li><li><span><a href="#-torch.vstack(...)" data-toc-modified-id="-torch.vstack(...)-1.11.5"><span class="toc-item-num">1.11.5&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.vstack.html#torch.vstack" rel="nofollow" target="_blank"> <code>torch.vstack(...)</code></a></a></span></li><li><span><a href="#-torch.hstack(...)" data-toc-modified-id="-torch.hstack(...)-1.11.6"><span class="toc-item-num">1.11.6&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.vstack.html#torch.hstack" rel="nofollow" target="_blank"> <code>torch.hstack(...)</code></a></a></span></li><li><span><a href="#torch.unsqueeze()-/-torch.squeeze()" data-toc-modified-id="torch.unsqueeze()-/-torch.squeeze()-1.11.7"><span class="toc-item-num">1.11.7&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze" rel="nofollow" target="_blank"><code>torch.unsqueeze() / torch.squeeze()</code></a></a></span></li><li><span><a href="#torch.where(a,-b,-c)" data-toc-modified-id="torch.where(a,-b,-c)-1.11.8"><span class="toc-item-num">1.11.8&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.where.html#torch.where" rel="nofollow" target="_blank"><code>torch.where(a, b, c)</code></a></a></span></li><li><span><a href="#torch.max(...)-/-torch.min(...)" data-toc-modified-id="torch.max(...)-/-torch.min(...)-1.11.9"><span class="toc-item-num">1.11.9&nbsp;&nbsp;</span><code>torch.max(...) / torch.min(...)</code></a></span></li><li><span><a href="#-torch.arange(...)" data-toc-modified-id="-torch.arange(...)-1.11.10"><span class="toc-item-num">1.11.10&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange" rel="nofollow" target="_blank"> <code>torch.arange(...)</code></a></a></span></li><li><span><a href="#-torch.linspace(...)" data-toc-modified-id="-torch.linspace(...)-1.11.11"><span class="toc-item-num">1.11.11&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace" rel="nofollow" target="_blank"> <code>torch.linspace(...)</code></a></a></span></li><li><span><a href="#-torch.logspace(...)" data-toc-modified-id="-torch.logspace(...)-1.11.12"><span class="toc-item-num">1.11.12&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.logspace.html#torch.logspace" rel="nofollow" target="_blank"> <code>torch.logspace(...)</code></a></a></span></li><li><span><a href="#torch.float(...)" data-toc-modified-id="torch.float(...)-1.11.13"><span class="toc-item-num">1.11.13&nbsp;&nbsp;</span><code>torch.float(...)</code></a></span></li><li><span><a href="#torch.exp(...)/torch.sum(...)" data-toc-modified-id="torch.exp(...)/torch.sum(...)-1.11.14"><span class="toc-item-num">1.11.14&nbsp;&nbsp;</span><code>torch.exp(...)</code>/<code>torch.sum(...)</code></a></span></li></ul></li><li><span><a href="#Matrix-Operation" data-toc-modified-id="Matrix-Operation-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Matrix Operation</a></span></li><li><span><a href="#Saving-&amp;-Loading" data-toc-modified-id="Saving-&amp;-Loading-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Saving &amp; Loading</a></span></li><li><span><a href="#GPU-Support" data-toc-modified-id="GPU-Support-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>GPU Support</a></span></li></ul></li><li><span><a href="#Training-Models:" data-toc-modified-id="Training-Models:-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Training Models:</a></span><ul class="toc-item"><li><span><a href="#Basics-of-Derivatives-in-PyTorch" data-toc-modified-id="Basics-of-Derivatives-in-PyTorch-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Basics of Derivatives in PyTorch</a></span></li><li><span><a href="#Training-End-to-End-with-SGD" data-toc-modified-id="Training-End-to-End-with-SGD-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Training End-to-End with SGD</a></span></li><li><span><a href="#Calculating-Gradients" data-toc-modified-id="Calculating-Gradients-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Calculating Gradients</a></span></li><li><span><a href="#Stepping-With-a-Learning-Rate" data-toc-modified-id="Stepping-With-a-Learning-Rate-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Stepping With a Learning Rate</a></span></li><li><span><a href="#An-End-to-End-SGD-with-(2nd-degree-poly-regression)" data-toc-modified-id="An-End-to-End-SGD-with-(2nd-degree-poly-regression)-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>An End-to-End SGD with (2nd degree poly regression)</a></span><ul class="toc-item"><li><span><a href="#Step-1:-Initialize-the-parameters" data-toc-modified-id="Step-1:-Initialize-the-parameters-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Step 1: Initialize the parameters</a></span></li><li><span><a href="#Step-2:-Calculate-the-predictions" data-toc-modified-id="Step-2:-Calculate-the-predictions-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>Step 2: Calculate the predictions</a></span></li><li><span><a href="#Step-3:-Calculate-the-loss" data-toc-modified-id="Step-3:-Calculate-the-loss-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>Step 3: Calculate the loss</a></span></li><li><span><a href="#Step-4:-Calculate-the-gradients" data-toc-modified-id="Step-4:-Calculate-the-gradients-2.5.4"><span class="toc-item-num">2.5.4&nbsp;&nbsp;</span>Step 4: Calculate the gradients</a></span></li><li><span><a href="#Step-5:-Step-the-weights." data-toc-modified-id="Step-5:-Step-the-weights.-2.5.5"><span class="toc-item-num">2.5.5&nbsp;&nbsp;</span>Step 5: Step the weights.</a></span></li><li><span><a href="#Step-6:-Repeat-the-process" data-toc-modified-id="Step-6:-Repeat-the-process-2.5.6"><span class="toc-item-num">2.5.6&nbsp;&nbsp;</span>Step 6: Repeat the process</a></span></li><li><span><a href="#Step-7:-stop" data-toc-modified-id="Step-7:-stop-2.5.7"><span class="toc-item-num">2.5.7&nbsp;&nbsp;</span>Step 7: stop</a></span></li></ul></li><li><span><a href="#Training-in-Using-Net:" data-toc-modified-id="Training-in-Using-Net:-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Training in Using Net:</a></span></li></ul></li><li><span><a href="#torch.nn-/-torch.nn.functional" data-toc-modified-id="torch.nn-/-torch.nn.functional-3"><span class="toc-item-num">3&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/nn.html" rel="nofollow" target="_blank">torch.nn</a> / <a href="https://pytorch.org/docs/stable/nn.functional.html" rel="nofollow" target="_blank">torch.nn.functional</a></a></span><ul class="toc-item"><li><span><a href="#Models" data-toc-modified-id="Models-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Models</a></span></li><li><span><a href="#torch.nn.LossFunctioons" data-toc-modified-id="torch.nn.LossFunctioons-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/nn.html#loss-functions" rel="nofollow" target="_blank">torch.nn.LossFunctioons</a></a></span><ul class="toc-item"><li><span><a href="#nn.MSELoss" data-toc-modified-id="nn.MSELoss-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss" rel="nofollow" target="_blank"><code>nn.MSELoss</code></a></a></span></li><li><span><a href="#nn.NLLLoss" data-toc-modified-id="nn.NLLLoss-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html#torch.nn.NLLLoss" rel="nofollow" target="_blank"><code>nn.NLLLoss</code></a></a></span></li><li><span><a href="#nn.CrossEntropyLoss" data-toc-modified-id="nn.CrossEntropyLoss-3.2.3"><span class="toc-item-num">3.2.3&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss" rel="nofollow" target="_blank"><code>nn.CrossEntropyLoss</code></a></a></span></li><li><span><a href="#nn.BCELoss" data-toc-modified-id="nn.BCELoss-3.2.4"><span class="toc-item-num">3.2.4&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html#torch.nn.BCELoss" rel="nofollow" target="_blank"><code>nn.BCELoss</code></a></a></span></li></ul></li><li><span><a href="#Activation-Funcrions" data-toc-modified-id="Activation-Funcrions-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Activation Funcrions</a></span><ul class="toc-item"><li><span><a href="#torch.relu(...):" data-toc-modified-id="torch.relu(...):-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span><code>torch.relu(...)</code>:</a></span></li><li><span><a href="#torch.tanh(...):" data-toc-modified-id="torch.tanh(...):-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span><code>torch.tanh(...)</code>:</a></span></li><li><span><a href="#softmax(...):" data-toc-modified-id="softmax(...):-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span><code>softmax(...)</code>:</a></span></li><li><span><a href="#torch.sigmoid(...):" data-toc-modified-id="torch.sigmoid(...):-3.3.4"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span><code>torch.sigmoid(...)</code>:</a></span></li></ul></li></ul></li><li><span><a href="#torch.optim-(Optimizers)" data-toc-modified-id="torch.optim-(Optimizers)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/optim.html" rel="nofollow" target="_blank">torch.optim (Optimizers)</a></a></span></li><li><span><a href="#torch.utils.data" data-toc-modified-id="torch.utils.data-5"><span class="toc-item-num">5&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/data.html" rel="nofollow" target="_blank">torch.utils.data</a></a></span><ul class="toc-item"><li><span><a href="#torch.util.data.Dataset(...):" data-toc-modified-id="torch.util.data.Dataset(...):-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset" rel="nofollow" target="_blank">torch.util.data.Dataset(...)</a>:</a></span></li><li><span><a href="#torch.util.data.DataLoader(...):" data-toc-modified-id="torch.util.data.DataLoader(...):-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span><a href="https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader" rel="nofollow" target="_blank">torch.util.data.DataLoader(...)</a>:</a></span></li><li><span><a href="#Primer-of-Dataset" data-toc-modified-id="Primer-of-Dataset-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Primer of Dataset</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Create-your-Own-Dataset:" data-toc-modified-id="Create-your-Own-Dataset:-5.3.0.1"><span class="toc-item-num">5.3.0.1&nbsp;&nbsp;</span>Create your Own Dataset:</a></span></li><li><span><a href="#Create-your-Own-Transformers:" data-toc-modified-id="Create-your-Own-Transformers:-5.3.0.2"><span class="toc-item-num">5.3.0.2&nbsp;&nbsp;</span>Create your Own Transformers:</a></span></li><li><span><a href="#Compose-Several-Transformers:" data-toc-modified-id="Compose-Several-Transformers:-5.3.0.3"><span class="toc-item-num">5.3.0.3&nbsp;&nbsp;</span>Compose Several Transformers:</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#torchvision" data-toc-modified-id="torchvision-6"><span class="toc-item-num">6&nbsp;&nbsp;</span><a href="https://pytorch.org/vision/stable/index.html" rel="nofollow" target="_blank">torchvision</a></a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#torchvision.datasets(...):" data-toc-modified-id="torchvision.datasets(...):-6.0.0.1"><span class="toc-item-num">6.0.0.1&nbsp;&nbsp;</span><a href="https://pytorch.org/vision/stable/datasets.html" rel="nofollow" target="_blank">torchvision.datasets(...)</a>:</a></span></li><li><span><a href="#torchvision.transforms:" data-toc-modified-id="torchvision.transforms:-6.0.0.2"><span class="toc-item-num">6.0.0.2&nbsp;&nbsp;</span><a href="https://pytorch.org/vision/stable/transforms.html" rel="nofollow" target="_blank">torchvision.transforms</a>:</a></span></li><li><span><a href="#Pretrained-Torchvision-Models:" data-toc-modified-id="Pretrained-Torchvision-Models:-6.0.0.3"><span class="toc-item-num">6.0.0.3&nbsp;&nbsp;</span><a href="https://pytorch.org/vision/stable/models.html#" rel="nofollow" target="_blank">Pretrained Torchvision Models</a>:</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#End-to-End-Deep-Learning-with-PyTorch" data-toc-modified-id="End-to-End-Deep-Learning-with-PyTorch-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>End to End Deep Learning with PyTorch</a></span></li></ul></div>

In [1]:
# These are the libraries will be used for this lab.
from collections import OrderedDict

import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets as dsets
import torchvision.transforms as transforms

from random import shuffle

<font style='color:red' size=5>Reference:</font>

- [Introduction to Pytorch Code Examples by Stanford University](https://cs230.stanford.edu/blog/pytorch/)
- [Classifying Images of Hand Signs by Stanford University](https://cs230.stanford.edu/blog/handsigns/)
- [Named Entity Recognition Tagging by Stanford University](https://cs230.stanford.edu/blog/namedentity/)
- [PYTORCH TUTORIALS by PYTORCH.org](https://pytorch.org/tutorials/)
- []()
- [PyTorch Notes](https://ikhlestov.github.io/pages/machine-learning/pytorch-notes/#work-with-cuda)

## torch.Tensor

### Instentiation of Tensor

In [ ]:
L1 = [[1,2,3], [6,5,4], [7,8,9]]
A1 = np.array(L1)

T1_0 = torch.Tensor(L1)      # Tensor from Python List
T1_1 = torch.Tensor(A1)      # Tensor from np.array()
T1_2 = torch.Tensor(4,5) 

T1_2

### Initiation of Tensor using Factory Methods

In [ ]:
T1_FM_0 = torch.tensor([1, 3, 2, 4])
T1_FM_1 = torch.full((3,3), 2.0)
T1_FM_2 = torch.ones((3,3))
T1_FM_3 = torch.eye(3)

print(T1_FM_0, T1_FM_1, T1_FM_2, T1_FM_3, sep='\n\n')

In [ ]:
T1_stk_1 = torch.stack((T1_FM_1, T1_FM_3))
T1_stk_2 = torch.stack((T1_FM_1, T1_FM_2, T1_FM_3), dim=1)

print(T1_stk_1, T1_stk_2, sep='\n\n')

In [ ]:
T1_cat_1 = torch.cat([T1_FM_1, T1_FM_2], dim=0)
T1_cat_2 = torch.cat([T1_FM_1, T1_FM_2], dim=1)

print(T1_cat_1, T1_cat_2, sep='\n\n') 

### Random Initiation of Tensor

In [ ]:
T1_RN_0 = torch.randint(1,10,(5,))
T1_RN_1 = torch.randint(1,10,(3,3), dtype=torch.float32)
T1_RN_2 = torch.randn(5, 3)
T1      = torch.Tensor(5, 3).uniform_(-1, 1)
T1      = torch.from_numpy(np.random.rand(5, 3)).type()

In [ ]:
# print(T1_RN_0, T1_RN_1, T1_RN_2, T1, T1, sep='\n\n')

### Types and Attributes

|Data type |Tensor|
|----------|------|
|32-bit floating point|	torch.FloatTensor|
|64-bit floating point|	torch.DoubleTensor|
|16-bit floating point|	torch.HalfTensor|
|8-bit integer (unsigned)|torch.ByteTensor|
|8-bit integer (signed)|torch.CharTensor|
|16-bit integer (signed)|torch.ShortTensor|
|32-bit integer (signed)|torch.IntTensor|
|64-bit integer (signed)|torch.LongTensor|

In [62]:
T2 = torch.full([3,3], 3.0)
print(T2.shape, T2.ndim, T2.data, T2.grad, sep='\n')

torch.Size([3, 3])
2
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
None


In [63]:
print(T2.size(), T2.ndimension(), T2.numel(), sep='\n')

torch.Size([3, 3])
2
9


In [64]:
print(T2.data, T2.grad_fn, T2.grad, T2.is_leaf, T2.requires_grad, sep='\n')

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
None
None
True
False


In [ ]:
ßT2_np = T2.numpy()
T2 = torch.from_numpy(T2_np)

In [ ]:
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})
new_tensor = torch.from_numpy(df.values)

df.values, df.values.dtype, new_tensor.dtype

In [ ]:
T2_one_elm_tensor = torch.tensor([2.0])
T2_one_elm_tensor.item()

In [ ]:
## Error: only one element tensors can be converted to Python scalars
# T2.item()

<!--Empty Space for separating topics-->

### Indexing and Slicing

You can use rectangular brackets to access the different elements of the tensor. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3X3 tensor:  

In [ ]:
A = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2index1.png" width=500 alt="Matrix Structure Introduce">

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2index.png" width="500" alt="Example of Matrix Index">

In [ ]:
print(A[1, 2])

<!--Empty Space for separating topics-->

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2_index2.png" width="500" alt="Example of Matrix Index" />

In [ ]:
A[0][0]

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2sliceing.png" width="500" alt="Example of Matrix Index and Slicing" />

In [ ]:
print(A[0, 0:2])

<!--Empty Space for separating topics-->

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2slicing2.png" width="500" alt="Example of Matrix Index and Slicing" />

In [ ]:
print(A[1:3, 2])

In [ ]:
print(A[1:3, 2])

### Tensor Arithmatics

### Tensor Addition

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2add.png" width="500" alt="Tensor Addition in 2D">

In [ ]:
X = torch.tensor([[1, 0],[0, 1]]) 
Y = torch.tensor([[2, 1],[1, 2]])
X_plus_Y = X + Y
print(X_plus_Y)

### Scalar Multiplication

Multiplying a tensor by a scalar is identical to multiplying a matrix by a scaler. If you multiply the matrix <b>Y</b> by the scalar 2, you simply multiply every element in the matrix by 2 as shown in the figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2scaller_mult.png" width="500" alt="The product of tensor and scalar">

In [ ]:
Y = torch.tensor([[2, 1], [1, 2]]) 
two_Y = 2 * Y
print(two_Y)

<!--Empty Space for separating topics-->

### Element-wise Product/Hadamard Product

Multiplication of two tensors corresponds to an element-wise product or Hadamard product.  Consider matrix the <b>X</b> and <b>Y</b> with the same size. The Hadamard product corresponds to multiplying each of the elements at the same position, that is, multiplying elements with the same color together. The result is a new matrix that is the same size as matrix <b>X</b> and <b>Y</b> as shown in the following figure:

 <a><img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2tensor_pruduct.png" width=500 align="center"> </a>


In [ ]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print(X_times_Y)

<!--Empty Space for separating topics-->

### Broadcasting

In [ ]:
torch.manual_seed(1);
pred = torch.randn((4,))
pred.sigmoid()
# pred

In [ ]:
xb = torch.randn((4,3)); xb

In [ ]:
print(xb.sigmoid(), xb[0].sigmoid(), sep='\n\n')

In [ ]:
targets = torch.randint(0,3,(4,3))
inputs = xb.sigmoid()
print(targets, inputs, sep='\n\n')

In [ ]:
fltr = -torch.where(targets==1, inputs, 1-inputs).log(); fltr

In [ ]:
# Binary Cross Entropy
bce = -torch.where(targets==1, inputs, 1-inputs).log().mean(); bce

In [ ]:
L1 = [x.mean() for x in fltr]; L1

In [ ]:
L2 = torch.tensor(L1).mean(); L2

### Usefull Functions

In [ ]:
T7_0 = torch.randperm(6)
T7_1 = torch.randint(0,5,(4,4))

print(T7_0, T7_1, sep='\n\n')

#### [`Tensor.data_ptr(...)`](https://pytorch.org/docs/stable/tensors.html)

In [ ]:
T7_0.data_ptr(), id(T7_0)

#### `torch.view(...)`

In [ ]:
print(T7_0.view(-1,8), T7_0.view(4,4), T7_0.view(8,-1), sep='\n')

In [ ]:
T_7_2 = torch.linspace(-1, 1, 10).view(-1, 1); T_7_2

<!--Empty Space for separating topics-->

####  [`torch.cat(...)`](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [ ]:
concate2 = torch.cat([T7_0, T7_0], dim=0)
concate1 = torch.cat([T7_0, T7_0], dim=1)

concate1, concate2

#### [ `torch.stack(...)`](https://pytorch.org/docs/stable/generated/torch.stack.html#torch.stack)

In [ ]:
# accs = [10.0, 5.0, 7.0]
accs = [torch.tensor(10.0), torch.tensor(5.0), torch.tensor(7.0)]
stk = round(torch.stack(accs).mean().item(), 4)

#### [ `torch.vstack(...)`](https://pytorch.org/docs/stable/generated/torch.vstack.html#torch.vstack)

#### [ `torch.hstack(...)`](https://pytorch.org/docs/stable/generated/torch.vstack.html#torch.hstack)

####  [`torch.unsqueeze() / torch.squeeze()`](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze)

In [ ]:
unsqz = T7_0.unsqueeze(1)
print(unsqz, unsqz.squeeze(), T7_1.unsqueeze(1), sep='\n\n')

In [ ]:
torch.random??

####  [`torch.where(a, b, c)`](https://pytorch.org/docs/stable/generated/torch.where.html#torch.where)

This is the same as running the list comprehension 
 - ``` python
[b[i] if a[i] else c[i] for i in range(len(a))]
```

- ``` python
xarr = torch.tensor([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = torch.tensor([2.1, 2.2, 2.3, 2.4, 2.5])
cond = torch.tensor([True, False, True, True, False])
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
```

In [ ]:
L7_0 = [0]*5 + [1]*5
shuffle(L7_0)
targets = torch.tensor(L7_0, dtype=torch.float32)
shuffle(L7_0)
predictions = torch.tensor(T7_2, dtype=torch.float32)
# predictions = torch.randperm(5, dtype=torch.float32)
whr = torch.where(targets==1, 1-predictions, predictions).mean()
print(targets, predictions, whr, sep='\n')

#### `torch.max(...) / torch.min(...)`

In [ ]:
T7_2 = torch.randint(-5, 5, (9,)).float().view(-1,3)

print(
    T7_2, T7_2.max(1), 
    T7_2.max(torch.tensor([2])), 
    T7_2.min(torch.tensor([0.0])), sep='\n\n')

type(T7_2.max(1))

In [ ]:
z = torch.tensor([[2,5,0]])
value, index = z.max(1)
value, index

#### [ `torch.arange(...)`](https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange)

* `arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)`

In [ ]:
a1 = torch.arange(-1, 1.01, 0.5)
a2 = torch.arange(-1, 0.99, 0.5)
a3 = torch.arange(-1, 1, 0.5)

print(a1, a2, a3, sep='\n\n')

#### [ `torch.linspace(...)`](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace)

* `linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)`

In [ ]:
l1 = torch.linspace(-1, 1, 5)
l2 = torch.linspace(-1, 1.1, 5)
l3 = torch.linspace(-1, .99, 5)

print(l1, l2, l3, sep='\n\n')

#### [ `torch.logspace(...)`](https://pytorch.org/docs/stable/generated/torch.logspace.html#torch.logspace)

In [ ]:
torch.logspace(start=-10, end=10, steps=5)
torch.logspace(start=0.1, end=1.0, steps=5)
torch.logspace(start=2, end=2, steps=1, base=2)

#### `torch.float(...)`

In [ ]:
time = torch.arange(0,20).float(); time

#### `torch.exp(...)`/`torch.sum(...)`

In [ ]:
# help(torch.sum)

In [57]:
def softmax(x): return (x.exp()/(x.exp().sum(-1, keepdim=True)))

In [29]:
torch.random.manual_seed(42);
X = torch.randn((6,3))*10
W = torch.randn(3, 4)
Z = X@W
Z

tensor([[-24.5198, -40.3251, -10.6257,   3.2256],
        [ 25.0067,   6.4096,   3.9762,   5.7944],
        [ -1.3002, -21.8870,  -2.8411,   7.4455],
        [ 30.7034,  12.0852,   7.9834,   8.9524],
        [ -4.8147,   1.2925,  -0.3343,  -1.8650],
        [-11.4197, -11.3090,  -4.6375,  -1.9637]])

In [38]:
acts = Z.exp()/Z.exp().sum(-1, keepdim=True); acts

tensor([[8.9197e-13, 1.2195e-19, 9.6485e-07, 1.0000e+00],
        [1.0000e+00, 8.3828e-09, 7.3550e-10, 4.5313e-09],
        [1.5911e-04, 1.8237e-13, 3.4081e-05, 9.9981e-01],
        [1.0000e+00, 8.2078e-09, 1.3579e-10, 3.5783e-10],
        [1.7940e-03, 8.0559e-01, 1.5835e-01, 3.4266e-02],
        [7.3160e-05, 8.1722e-05, 6.4525e-02, 9.3532e-01]])

In [44]:
acts.sum(1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [36]:
sm_acts = torch.softmax(Z, dim=1); sm_acts

tensor([[8.9197e-13, 1.2195e-19, 9.6485e-07, 1.0000e+00],
        [1.0000e+00, 8.3828e-09, 7.3549e-10, 4.5313e-09],
        [1.5911e-04, 1.8237e-13, 3.4081e-05, 9.9981e-01],
        [1.0000e+00, 8.2078e-09, 1.3579e-10, 3.5783e-10],
        [1.7940e-03, 8.0559e-01, 1.5835e-01, 3.4266e-02],
        [7.3160e-05, 8.1722e-05, 6.4525e-02, 9.3532e-01]])

In [ ]:
sm_score = softmax(acts); sm_score

In [ ]:
sm_score.sum(-1, keepdim=True)

### Matrix Operation

We can also apply matrix multiplication to two tensors, if you have learned linear algebra, you should know that in the multiplication of two matrices order matters. This means if <i>X * Y</i> is valid, it does not mean <i>Y * X</i> is valid. The number of columns of the matrix on the left side of the multiplication sign must equal to the number of rows of the matrix on the right side.

First, let us create a tensor <code>X</code> with size 2X3. Then, let us create another tensor <code>Y</code> with size 3X2. Since the number of columns of <code>X</code> is equal to the number of rows of <code>Y</code>. We are able to perform the multiplication.

We use <code>torch.mm()</code> for calculating the multiplication between tensors with different sizes.

In [7]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B) # A @ B

print(A, B, A_times_B, sep='\n\n')

tensor([[0, 1, 1],
        [1, 0, 1]])

tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])

tensor([[0, 2],
        [0, 2]])


In [8]:
torch.transpose(A,0,1) == torch.t(A), torch.t(A) == A.T

(tensor([[True, True],
         [True, True],
         [True, True]]),
 tensor([[True, True],
         [True, True],
         [True, True]]))

In [27]:
x = torch.tensor([[3, 4], [2, 1]])
w = torch.tensor([10, 20])
b = torch.tensor([0.15])
x@w.view(2,-1)

tensor([[110],
        [ 40]])

In [12]:
wx = torch.dot(x, w) + b
wx2 = x@w.T + b

a = wx.sigmoid()
a2 = torch.sigmoid(wx)
print(wx, wx2, a, a2)

tensor([0.2675]) tensor([0.2675]) tensor([0.5665]) tensor([0.5665])


### Saving & Loading

In [ ]:
model = nn.Linear(1,1)
torch.save(model.state_dict(), 'data/test_model_saving.pt')

In [ ]:
# Create a new linear regression model object
model_prebuilt = nn.Linear(1,1)

# Assign the best model to model_best
model_param = torch.load('data/test_model_saving.pt')
model_prebuilt.load_state_dict(model_param)

In [ ]:
def save_checkpoint(state, filename="my_checkpoint.pth.tar"):
    print("=> Saving checkpoint")
    torch.save(state, filename)


def load_checkpoint(checkpoint, model, optimizer):
    print("=> Loading checkpoint")
    model.load_state_dict(checkpoint["state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer"])

### GPU Support

In [ ]:
x = torch.cuda.HalfTensor(5, 3).uniform_(-1, 1)
y = torch.cuda.HalfTensor(3, 5).uniform_(-1, 1)
torch.matmul(x, y)

In [ ]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
x = x.cpu()
print(x)

In [ ]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))

## Training Models:

### Basics of Derivatives in PyTorch

In [ ]:
x = torch.tensor(3.0)
print(x, x.requires_grad, x.grad, x.grad_fn, sep='\n')

In [ ]:
y = x**2
print(y, y.requires_grad, y.grad, y.grad_fn, sep='\n')

In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2
y.backward()

In [ ]:
print(x, x.requires_grad, x.grad, x.grad_fn, sep='\n')

<b style='color:red'> Notes: </b>
- **x** holds derivatives of **y** with respect to **x** at **x**, **$\frac{dy}{dx}(x)$**
- **x** does not hold any **gradient function**
- **y** holds **gradient function**
- **y** does not hold any derivative, **$\frac{dy}{dx}$**

In [ ]:
print(y, y.requires_grad, y.retain_grad(), y.grad_fn, sep='\n')

In [ ]:
w = torch.tensor([1.0, 2.0, 2.0], requires_grad=True)
y = w**2
# y.backward()     # ERRORS !!

In [ ]:
print(y, y.requires_grad, y.grad_fn, sep='\n')

<b style='color:red'> Notes: </b>
- While `x.requires_grad` (a attribute of independent variavle **x**) is set true, then `y.requires_grad` is automaticaly set true.

In [ ]:
x1 = torch.tensor([2.0], requires_grad=True)
x2 = torch.tensor([3.0], requires_grad=True)
z = x1*x2 + 2*x1*x2**2

In [ ]:
z.backward()

In [ ]:
print(z, z.requires_grad, z.grad_fn, sep='\n')

In [ ]:
print(x1.grad, x2.grad)

### Training End-to-End with SGD

In [ ]:
tensor = torch.tensor

In [ ]:
def plot_function(f, tx=None, ty=None, title=None, min=-2, max=2, figsize=(6,4)):
    x = torch.linspace(min,max)
    fig,ax = plt.subplots(figsize=figsize)
    ax.plot(x,f(x))
    if tx is not None: ax.set_xlabel(tx)
    if ty is not None: ax.set_ylabel(ty)
    if title is not None: ax.set_title(title)

In [ ]:
def f(x): return x**2

In [ ]:
# plot_function(f, 'x', 'x**2')

In [ ]:
plot_function(f, 'x', '$x^2$')
plt.scatter(-1.5, f(-1.5), color='red');

### Calculating Gradients

In [ ]:
xt = tensor(3.).requires_grad_(); xt

In [ ]:
yt = f(xt)
yt #; yt.grad

In [ ]:
yt.backward(); yt

In [ ]:
xt.grad

In [ ]:
xt = tensor([3.,4.,10.]).requires_grad_()
xt

In [ ]:
def f(x): return (x**2).sum()

yt = f(xt)
yt

In [ ]:
yt.backward()
xt.grad

### Stepping With a Learning Rate

### An End-to-End SGD with (2nd degree poly regression)

In [ ]:
time = torch.arange(0,20).float(); time

In [ ]:
speed = torch.randn(20)*3 + 0.75*(time-9.5)**2 + 1
plt.scatter(time, speed);

In [ ]:
# Predictor, Y_hat
def f(t, params):
    a,b,c = params
    return a*(t**2) + (b*t) + c

In [ ]:
# Loss Function
def mse(preds, targets): return ((preds-targets)**2).mean()

#### Step 1: Initialize the parameters

In [ ]:
params = torch.randn(3).requires_grad_(); params

In [ ]:
params.data

In [ ]:
params.grad

In [ ]:
orig_params = params.clone()

#### Step 2: Calculate the predictions

In [ ]:
preds = f(time, params) ## W = params, time = X

In [ ]:
def show_preds(preds, ax=None):
    if ax is None: ax=plt.subplots()[1]
    ax.scatter(time, speed)
    ax.scatter(time, preds.detach().numpy(), color='red')
    ax.set_ylim(-300,100)

In [ ]:
show_preds(preds)

#### Step 3: Calculate the loss

In [ ]:
loss = mse(preds, speed) ## speed == target (y)
loss

#### Step 4: Calculate the gradients

In [ ]:
loss.backward()
params.grad

In [ ]:
params.data

In [ ]:
params.grad * 1e-5

In [ ]:
params

In [ ]:
params.grad

In [ ]:
params.data #; type(params.data)

#### Step 5: Step the weights. 

In [ ]:
lr = 1e-5
params.data -= lr * params.grad.data
params.grad = None

In [ ]:
params

In [ ]:
preds = f(time, params)
mse(preds, speed)

In [ ]:
show_preds(preds)

In [ ]:
def apply_step(params, prn=True):
    preds = f(time, params)
    loss = mse(preds, speed)
    loss.backward()
    params.data -= lr * params.grad.data
    params.grad = None
    if prn: print("loss = ", loss.item(), ";\t\t params = ", params)
    return preds

#### Step 6: Repeat the process 

In [ ]:
for i in range(10): apply_step(params)

In [ ]:
params

In [ ]:
params = orig_params.detach().requires_grad_(); params

In [ ]:
_,axs = plt.subplots(2,4,figsize=(12,6))
for row in axs:    
    for ax in row: show_preds(apply_step(params, False), ax)
plt.tight_layout()

In [ ]:
params.data

#### Step 7: stop

### Training in Using Net:

In [ ]:
# help(DataLoader)

In [ ]:
# Define softmax classifier class

class SoftMax(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(SoftMax, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        
    # Prediction
    def forward(self, x):
        z = self.linear(x)
        return z

<b style='color:red'> Click Here to see Complete Training of Softmax Net</b>

<!---
input_dim, output_dim = 28*28, 10
learning_rate = 0.01
batch_size = 100

model = SoftMax(input_dim, output_dim)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

trn_ds = dsets.MNIST(root='~/Data', download=False, train=True, transform=transforms.ToTensor())
vld_ds = dsets.MNIST(root='~/Data', train=False, transform=transforms.ToTensor())

trn_dl = DataLoader(trn_ds, batch_size=batch_size)
vld_dl = DataLoader(vld_ds, batch_size=batch_size)

epochs = 10
losses = []
accuracies = []

for epoch in range(epochs):
    for xb, yb in trn_dl:
        z    = model(xb.view(-1, 28*28))
        loss = criterion(z, yb)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    correct = 0
    for xb, yb in vld_dl:
        y = model(xb.view(-1, 28*28))
        _max, idx = torch.max(y.data, axis=1)
        correct += (yb == idx).sum()
    
    losses.append(loss)
    accuracies.append(correct/len(vld_ds))        
        
        
-->

In [ ]:
# Plot the loss and accuracy

fig, ax1 = plt.subplots()
color = 'tab:red'
ax1.plot(losses, color=color)
ax1.set_xlabel('epoch',color=color)
ax1.set_ylabel('total loss',color=color)
ax1.tick_params(axis='y', color=color)
    
ax2 = ax1.twinx()  
color = 'tab:blue'
ax2.set_ylabel('accuracy', color=color)  
ax2.plot( accuracies, color=color)
ax2.tick_params(axis='y', color=color)
fig.tight_layout()

## [torch.nn](https://pytorch.org/docs/stable/nn.html) / [torch.nn.functional](https://pytorch.org/docs/stable/nn.functional.html)

### Models

`nn.Module.parameter(...)`, `nn.Module.state_dict(...)`

In [ ]:
lin_mdl = nn.Linear(3,1)

In [ ]:
print(list(lin_mdl.parameters()), lin_mdl.state_dict(), sep='\n\n')

In [ ]:
[*lin_mdl.parameters()]

In [ ]:
# Create Net model class

class NetModuleList(nn.Module):
    
    # Constructor
    def __init__(self, Layers):
        super(Net, self).__init__()
        self.hidden = nn.ModuleList()
        for input_size, output_size in zip(Layers, Layers[1:]):
            self.hidden.append(nn.Linear(input_size, output_size))
    
    # Prediction
    def forward(self, x):
        L = len(self.hidden)
        for (l, linear_transform) in zip(range(L), self.hidden):
            if l < L - 1: x = F.relu(linear_transform(x))
            else: activation = linear_transform(x)
        return x

In [5]:
model_seq1 = nn.Sequential(
          nn.Linear(2, 50),
          nn.ReLU(),
          nn.Linear(),
          nn.ReLU()
        )

model_seq2 = nn.Sequential(OrderedDict([
          ('lin1', nn.Linear(2,50)),
          ('relu1', nn.ReLU()),
          ('lin2', nn.Linear(20,64,5)),
          ('relu2', nn.ReLU())
        ]))

In [ ]:
# Define the function for training the model

def train(data_set, model, criterion, train_loader, optimizer, epochs=100):
    LOSS = []
    ACC = []
    for epoch in range(epochs):
        for x, y in train_loader:
            optimizer.zero_grad()
            yhat = model(x)
            loss = criterion(yhat, y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            LOSS.append(loss.item())           # Loss for each batch
        
        ACC.append(accuracy(model, data_set))  # Accuracy for each epoch
    
    fig, ax1 = plt.subplots()
    color = 'tab:red'
    ax1.plot(LOSS, color = color)
    ax1.set_xlabel('Iteration', color = color)
    ax1.set_ylabel('total loss', color = color)
    ax1.tick_params(axis = 'y', color = color)
    
    ax2 = ax1.twinx()  
    color = 'tab:blue'
    ax2.set_ylabel('accuracy', color = color)  # we already handled the x-label with ax1
    ax2.plot(ACC, color = color)
    ax2.tick_params(axis = 'y', color = color)
    fig.tight_layout()  # otherwise the right y-label is slightly clipped
    
    plt.show()
    return LOSS

In [ ]:
# Train the model with 1 hidden layer with 50 neurons

Layers = [2, 50, 3]
model = NetModuleList(Layers)
learning_rate = 0.10
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
train_loader = DataLoader(dataset=data_set, batch_size=20)
criterion = nn.CrossEntropyLoss()
LOSS = train(data_set, model, criterion, train_loader, optimizer, epochs=100)

plot_decision_regions_3class(model, data_set)

### [torch.nn.LossFunctioons](https://pytorch.org/docs/stable/nn.html#loss-functions)

#### [`nn.MSELoss`](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss)

#### [`nn.NLLLoss`](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html#torch.nn.NLLLoss)

#### [`nn.CrossEntropyLoss`](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss)

#### [`nn.BCELoss`](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html#torch.nn.BCELoss)

### Activation Funcrions

In [52]:
torch.random.manual_seed(42);
X = torch.randn((6,3))*10
W = torch.randn(3, 4)
Z = X@W
Z

tensor([[-24.5198, -40.3251, -10.6257,   3.2256],
        [ 25.0067,   6.4096,   3.9762,   5.7944],
        [ -1.3002, -21.8870,  -2.8411,   7.4455],
        [ 30.7034,  12.0852,   7.9834,   8.9524],
        [ -4.8147,   1.2925,  -0.3343,  -1.8650],
        [-11.4197, -11.3090,  -4.6375,  -1.9637]])

#### `torch.relu(...)`:

In [53]:
acts_rlu = torch.relu(Z); acts

tensor([[-1.0000, -1.0000, -1.0000,  0.9968],
        [ 1.0000,  1.0000,  0.9993,  1.0000],
        [-0.8618, -1.0000, -0.9932,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.9999,  0.8598, -0.3224, -0.9531],
        [-1.0000, -1.0000, -0.9998, -0.9614]])

#### `torch.tanh(...)`:

In [54]:
acts_th = torch.tanh(Z); acts

tensor([[-1.0000, -1.0000, -1.0000,  0.9968],
        [ 1.0000,  1.0000,  0.9993,  1.0000],
        [-0.8618, -1.0000, -0.9932,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.9999,  0.8598, -0.3224, -0.9531],
        [-1.0000, -1.0000, -0.9998, -0.9614]])

#### `softmax(...)`:

In [59]:
def softmax(x): return (x.exp()/(x.exp().sum(-1, keepdim=True)))

In [60]:
acts_sm = softmax(Z); acts

tensor([[-1.0000, -1.0000, -1.0000,  0.9968],
        [ 1.0000,  1.0000,  0.9993,  1.0000],
        [-0.8618, -1.0000, -0.9932,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.9999,  0.8598, -0.3224, -0.9531],
        [-1.0000, -1.0000, -0.9998, -0.9614]])

#### `torch.sigmoid(...)`:

In [56]:
acts_sig = torch.sigmoid(Z); acts

tensor([[-1.0000, -1.0000, -1.0000,  0.9968],
        [ 1.0000,  1.0000,  0.9993,  1.0000],
        [-0.8618, -1.0000, -0.9932,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.9999,  0.8598, -0.3224, -0.9531],
        [-1.0000, -1.0000, -0.9998, -0.9614]])

## [torch.optim (Optimizers)](https://pytorch.org/docs/stable/optim.html)

In [ ]:
from torch import optim

In [ ]:
# help(optim)
# help(optim.SGD)

## [torch.utils.data](https://pytorch.org/docs/stable/data.html)

In [1]:
from torch.utils.data import Dataset, DataLoader

### [torch.util.data.Dataset(...)](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset):

In [3]:
# help(Dataset)

- Dataset is an abstract class
- All datasets that represent a map from keys to data samples should subclass it. 
- All subclasses should overwrite `__getitem__()`, supporting fetching a data sample for a given key. Subclasses could also optionally overwrite `__len__()`, which is expected to return the size of the dataset by many Sampler implementations and the default options of DataLoader.

### [torch.util.data.DataLoader(...)](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader):

In [ ]:
# help(DataLoader)

- Combines a dataset and a sampler, and provides an iterable over the given dataset.

- The DataLoader supports both map-style and iterable-style datasets with single- or multi-process loading, customizing loading order and optional automatic batching (collation) and memory pinning.

```python
DataLoader(dataset, batch_size=1, shuffle=False, sampler=None, batch_sampler=None, num_workers=0, collate_fn=None, pin_memory=False, drop_last=False, timeout=0, worker_init_fn=None, multiprocessing_context=None, generator=None, *, prefetch_factor=2, persistent_workers=False)
```

Parameters:

- `dataset (Dataset)` $→$ dataset from which to load the data.

- `batch_size (int, optional)` $→$ how many samples per batch to load (default: 1).

- `shuffle (bool, optional)` $→$ set to True to have the data reshuffled at every epoch (default: False).

- `sampler (Sampler or Iterable, optional)` $→$ defines the strategy to draw samples from the dataset. Can be any Iterable with __len__ implemented. If specified, shuffle must not be specified.

- `batch_sampler (Sampler or Iterable, optional)` $→$ like sampler, but returns a batch of indices at a time. Mutually exclusive with batch_size, shuffle, sampler, and drop_last.

- `num_workers (int, optional)` $→$ how many subprocesses to use for data loading. 0 means that the data will be loaded in the main process. (default: 0)

- `collate_fn (callable, optional)` $→$ merges a list of samples to form a mini-batch of Tensor(s). Used when using batched loading from a map-style dataset.

- `pin_memory (bool, optional)` $→$ If True, the data loader will copy Tensors into CUDA pinned memory before returning them. If your data elements are a custom type, or your collate_fn returns a batch that is a custom type, see the example below.

- `drop_last (bool, optional)` $→$ set to True to drop the last incomplete batch, if the dataset size is not divisible by the batch size. If False and the size of dataset is not divisible by the batch size, then the last batch will be smaller. (default: False)

- `timeout (numeric, optional)` $→$ if positive, the timeout value for collecting a batch from workers. Should always be non-negative. (default: 0)

- `worker_init_fn (callable, optional)` $→$ If not None, this will be called on each worker subprocess with the worker id (an int in [0, num_workers - 1]) as input, after seeding and before data loading. (default: None)

- `generator (torch.Generator, optional)` $→$ If not None, this RNG will be used by RandomSampler to generate random indexes and multiprocessing to generate base_seed for workers. (default: None)

- `prefetch_factor (int, optional, keyword-only arg)` $→$ Number of samples loaded in advance by each worker. 2 means there will be a total of 2 * num_workers samples prefetched across all workers. (default: 2)

- `persistent_workers (bool, optional)` $→$ If True, the data loader will not shutdown the worker processes after a dataset has been consumed once. This allows to maintain the workers Dataset instances alive. (default: False)

### Primer of Dataset

##### Create your Own Dataset:

In [ ]:
# Define class for dataset
class toy_set(Dataset):
    
    # Constructor with defult values 
    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform
     
    # Getter
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform: sample = self.transform(sample)     
        return sample
    
    # Get Length
    def __len__(self):
        return self.len

- The dataset object is an Iterable
- The dataset object is Indexable

In [ ]:
our_dataset = toy_set()
print(our_dataset)
print(len(our_dataset))
print(our_dataset[0])

##### Create your Own Transformers:

You can also create a class for transforming the data. In this case, we will try to add 1 to x and multiply y by 2:

In [ ]:
class add_mult(object):
    
    # Constructor
    def __init__(self, addx = 1, muly = 2):
        self.addx = addx
        self.muly = muly
    
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

<!--Empty Space for separating topics-->

In [ ]:
a_m = add_mult()
data_set = toy_set()

In [ ]:
for i in range(3):
    x, y = data_set[i]
    print(f'Index: {i}; Original x: {x}; Original y: {y}')
    x_, y_ = a_m(data_set[i])
    print(f'Index: {i}; Transformed x: {x_}; Transformed y: {y_}')

<!--Empty Space for separating topics-->

The same result is obtained using following method.

In [ ]:
cust_data_set = toy_set(transform = a_m)

In [ ]:
for i in range(3):
    x, y = cust_data_set[i]
    print(f'Index: {i}; Transformed x: {x}; Transformed y: {y}')

<!--Empty Space for separating topics-->

##### Compose Several Transformers:

In [ ]:
from torchvision import transforms 

You can compose multiple transforms on the dataset object. First, import <code>transforms</code> from <code>torchvision</code>:

The new <code>Compose</code> object will perform each transform concurrently as shown in this figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.3.1_trasform.png" width="500" alt="Compose PyTorch">

In [ ]:
class mult(object):
    
    # Constructor
    def __init__(self, mult = 100):
        self.mult = mult
        
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample

In [ ]:
# Combine the add_mult() and mult()
data_transform = transforms.Compose([add_mult(), mult()])
print("The combination of transforms (Compose): ", data_transform)

In [ ]:
data_transform(data_set[0])

In [ ]:
x,y = data_set[0]
x_,y_= data_transform(data_set[0])
print( 'Original x: ', x, 'Original y: ', y)

print( 'Transformed x_:', x_, 'Transformed y_:', y_)

In [ ]:
# Create a new toy_set object with compose object as transform
compose_data_set = toy_set(transform = data_transform)

Let us see what happened on index 0:
- The original value of <code>x</code> is <i>[2, 2]</i>, and the original value of <code>y</code> is [1].
- If we only applied <code>add_mult()</code> on the original dataset:
    - the <code>x</code> became <i>[3, 3]</i> and y became <i>[2]</i>. 
    
- Now apply both <code>add_mult()</code> and <code>mult()</code>: 
    - The result of x is <i>[300, 300]</i> and y is <i>[200]</i>. 
    - The calculation which is equavalent to the compose is <i> x = ([2, 2] + 1) x 100 = [300, 300], y = ([1] x 2) x 100 = 200</i>

Try to combine the <code>mult()</code> and <code>add_mult()</code> as <code>mult()</code> to be executed first. And apply this on a new <code>toy_set</code> dataset. Print out the first 3 elements in the transformed dataset.

##  [torchvision](https://pytorch.org/vision/stable/index.html)

In [ ]:
import torchvision.datasets as dsets
import torchvision.transforms as tfms

In [ ]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y; X_times_Y

##### [torchvision.datasets(...)](https://pytorch.org/vision/stable/datasets.html):

- All datasets are subclasses of `torch.utils.data.Dataset`, they have `__getitem__` and `__len__` methods implemented. Hence, they can all be passed to a `torch.utils.data.DataLoader` which can load multiple samples in parallel using `torch.multiprocessing` workers. For example:

In [ ]:
# help(dsets)

In [ ]:
# help(tfms)

In [ ]:
# help(tfms.ToTensor)

In [ ]:
# Import the prebuilt dataset into variable dataset
dataset = dsets.MNIST(
    root = '~/Data/', 
    train = False, 
    download = True, 
    transform = tfms.ToTensor()
)

In [ ]:
# Examine whether the elements in dataset MNIST are tuples, and what is in the tuple?

print("Type of the first element: ", type(dataset[0]))
print("The length of the tuple: ", len(dataset[0]))
print("The shape of the first element in the tuple: ", dataset[0][0].shape)
print("The type of the first element in the tuple", type(dataset[0][0]))
print("The second element in the tuple: ", dataset[0][1])
print("The type of the second element in the tuple: ", type(dataset[0][1]))
print("As the result, the structure of the first element in the dataset is (tensor([1, 28, 28]), tensor(7)).")

In [ ]:
# Plot the first element in the dataset
show_data(dataset[0])

In [ ]:
# Plot the second element in the dataset
show_data(dataset[1])

<!--Empty Space for separating topics-->

##### [torchvision.transforms](https://pytorch.org/vision/stable/transforms.html):

In [ ]:
# Combine two transforms: crop and convert to tensor. Apply the compose to MNIST dataset

croptensor_data_transform = tfms.Compose([tfms.CenterCrop(20), tfms.ToTensor()])
dataset = dsets.MNIST(
    root = '~/Data/', 
    train = False, 
    download = True, 
    transform = croptensor_data_transform
)

print("The shape of the first element in the first tuple: ", dataset[0][0].shape)

In [ ]:
# Plot the first element in the dataset
show_data(dataset[0], shape = (20, 20))

In [ ]:
# Plot the second element in the dataset
show_data(dataset[1],shape = (20, 20))

In [ ]:
# Construct the compose. Apply it on MNIST dataset. Plot the image out.

fliptensor_data_transform = tfms.Compose([tfms.RandomHorizontalFlip(p = 1),tfms.ToTensor()])

dataset = dsets.MNIST(
    root = '~/Data/', 
    train = False, 
    download = True, 
    transform = fliptensor_data_transform
)

show_data(dataset[1])

<!--Empty Space for separating topics-->

##### [Pretrained Torchvision Models](https://pytorch.org/vision/stable/models.html#):

## End to End Deep Learning with PyTorch

In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn


import torchvision.datasets as ds
import torchvision.transforms as tfms
import torchvision.models as mdls

In [ ]:
PATH = '/Users/a.momin/Data/bird_species/train/'